# Get ruby image from docker hub
FROM ruby:2.5.1-slim-stretch

# Copy the code from src folder (it could be any folder or this root) to the default ruby path
COPY ./src .

# Run the main.rb file
CMD [ "./main.rb" ]

