# Get python 3 image from docker hub
FROM python:3.7.0-slim

# Copy the code from src folder (it could be any folder or this root) to the default python path
COPY src/ .

# Run the main.py file
CMD [ "python", "./main.py" ]

