# Get php image 7.2.9 from docker hub
FROM php:7.2.9-apache

# Copy the code from src folder to the default php apache path 
COPY src/ /var/www/html

# Expose port 80 to be accessed by the running containers
EXPOSE 80

